### ISSUE TITLE
Error when reloading Curse project

### ISSUE THREAD

**Issue by DV8FromTheCode** [TheRandomLabs/CurseAPI#1]
I get the following error when using project.reload .

Code: https://pastebin.com/Gf2K1J2V

Error: https://pastebin.com/aCAP7y6z

**Comment by TheRandomLabs** [comment]
Whoa, I didn't expect anyone to actually use this yet. Thanks for reporting this anyway. I'll fix it now. Just so you know, you probably don't need to call reload there. I haven't written documentation yet either, so you'll have to look at how I use it in ChangelogGenerator or CurseAPI-Minecraft for examples.

**Comment by DV8FromTheCode** [comment]
ok, yea the api seems really cool and I plan to use it for discord to check when a addon is updated and inform users that it is.

**Comment by TheRandomLabs** [comment]
If you're going to be checking when a project is updated, I recommend calling `CurseProject.reload` instead.
