### ISSUE TITLE
[Suggestion] convenience method for getting serverPackFile URL/ID if file has one?

### ISSUE THREAD

**Issue by ROMVoid95** [TheRandomLabs/CurseAPI#18]
Was looking for this, had a CurseFile instance and if i skipped over it then disregard this lol. Not sure if its doable since this can be different depending on if file/project is a Mod or Modpack. 
i do know the API has the info using this endpoint 
https://addons-ecs.forgesvc.net/api/v2/addon/336617/file/2845309
serverPackFileId

**Comment by TheRandomLabs** [comment]
Ah, I overlooked this field. Thank you!

**Comment by ROMVoid95** [comment]
all good bud

**Comment by TheRandomLabs** [comment]
`CurseFile#alternateFileID()` and `CurseFile#alternateFile()` should work for server packs. :)
