### ISSUE TITLE
project.members().size() always 1

### ISSUE THREAD

**Issue by JayJay1989** [TheRandomLabs/CurseAPI#2]
If a project has multiple members (Owner, Contributors, Authors), only the first is added to the list.

![screenshot_3](https://user-images.githubusercontent.com/1212803/52643425-457d4b00-2edd-11e9-8231-c7094778113f.png)
gives as result:
project.members() => `[Member[type="Owner",username="JayJay_1989"]]`
project.members().size() => `1`

**Comment by TheRandomLabs** [comment]
Thanks for reporting this! It's fixed now. Just out of curiosity, what are you using this for? I didn't think anyone was using this.

**Comment by JayJay1989** [comment]
its for an discord bot. Simply get information about a project. 

Also for my api to download a specified modpack and  version on my gamepanel, without uploading the serverfiles my own.
I dont know if this script support this, once i get there, i modify it it to get it working. Expect some pull request ;)

I used my own one, written in php, but scraping is slow, like very slow. this script is a bit faster,

**Comment by TheRandomLabs** [comment]
Thanks!
