### ISSUE TITLE
File information cannot be retrieved for projects on BukkitDev

### ISSUE THREAD

**Issue by TheKinrar** [TheRandomLabs/CurseAPI#25]
I'm trying to list files for a Curse project but I get an empty set.

`CurseAPI.files(id).get().size()` returns 0 but `CurseAPI.project(id).get().name()` returns the right project name - in my testing case `WorldEdit` (with id = 31043).

Sorry if I'm doing something wrong.

**Comment by TheRandomLabs** [comment]
This is an issue on CurseForge's end; they're not providing any information for WorldEdit's files. Unfortunately, there's not much I can do about this.

**Comment by TheKinrar** [comment]
Oh, okay. Is that a common issue? Thanks for the quick reply. :)

**Comment by TheRandomLabs** [comment]
This is the first time I've seen this, but it might depend on the project type.

**Comment by TheKinrar** [comment]
Just looked into it and it seems that all BukkitDev plugins return no files info; maybe because as they are plugins they are not meant to be installed by the Twitch app.

Great library anyway and thanks for the help :)

**Comment by TheRandomLabs** [comment]
Yeah, that's a shame. Thank you!

**Comment by JamesPeters98** [comment]
I just posted this on the Twitch feedback forum to hopefully get someone to look at this!
https://twitch.uservoice.com/forums/915910-game-mods-curseforge/suggestions/40223431-bukkitdev-files-api

**Comment by TheRandomLabs** [comment]
Pretty sure the API is only meant for use by the launcher, so I doubt
anything will be done.

**Comment by TheRandomLabs** [comment]
Closing because this will likely never be fixed.
