### ISSUE TITLE
Any update on additional files?

### ISSUE THREAD

**Issue by Daan-Hoogland** [TheRandomLabs/CurseAPI#3]
For a few MC modpacks the additional files section holds the links to the server downloads. Noticed your todo flag in the CurseFile class and was wondering if you made any progress on that part yet.

**Comment by TheRandomLabs** [comment]
I haven't really been working on this, but I'll give it a shot this weekend.

**Comment by TheRandomLabs** [comment]
`CurseFile.hasParentFile`
`CurseFile.parentFile`
`CurseFile.parentFileID`
`CurseFile.additionalFiles`
