### ISSUE TITLE
[Suggestion] Get all projects from a User

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [TheRandomLabs/CurseAPI#5]
It would be cool to be able to provide a username or user url and get all projects the user made.
```
CurseUser usr = CurseUser.fromURL("https://www.curseforge.com/members/erdbeerbaerlp/projects");
for(CurseProject p : usr.getProjects()){
  //Do stuff
}
```

**Comment by TheRandomLabs** [comment]
This has been on my to-do list for a while.

Le mer. 17 juil. 2019 à 03:52, ErdbeerbaerLP <notifications@github.com> a
écrit :

**Comment by TheRandomLabs** [comment]
As far as I can tell, this is no longer possible.
